// Auto-generated by publish-to-website.py -- do not edit by hand.
// Last published: 2026-07-22 23:41:39.258177
window.SUITE_LISTINGS = [
  {
    "provider": "Regus",
    "address": "260 Ainslie Street, Floor 3",
    "priceText": null,
    "description": "",
    "sourceUrl": "https://www.regus.com",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "482 Driggs Ave",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "750 Manhattan Ave",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "115 Myrtle Ave, Floor 7 and 8",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "51-02 21st Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "300 Cadman Plaza West, Floor 12",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "30-10 41st Ave",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "35-01 36th Avenue, Floor 5",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "401 Park Avenue South, Floor 10",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "14 Wall Street, Floor 20",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "165 Broadway, Foor 23",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "41 Madison Avenue, Floor 31",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "600 3rd Avenue, Floor 2",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "100 Church Street, 8th Floor",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "101 Avenue of the Americas, Floor 9",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "99 Hudson Street, Floor 5",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "136 Madison Avenue, Floor 6",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "405 Lexington Ave, Chrysler Building, Floor 1, 7, 8, 9, 26",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "100 Park Avenue, 16th Floor",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "260 Madison Avenue, 8th Floor",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "200 Vesey Street, Brookfield Place, Floor 24",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "230 Park Avenue, Helmsley Building, Floor 3 and 4",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "1250 Broadway, 36th Floor",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "250 Park Avenue, 7th Floor",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "132 West 31st Street, Penn Plaza, Floor 9",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "112 West 34th Street 18th floor",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "118-35 Queens Boulevard,Forest Hills Tower, Suite 400 ",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "104 West 40th Street, Suite 400 and 500",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "445 Park Avenue",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "1177 6th Avenue Tower, Floor 5",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "14 Penn Plaza, 225 West 34th Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "5 Penn Plaza, Floor 19",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "West 14th Street, #200 Ground Floor and Suite 413",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "57 West 57th Street, 3rd and 4th Floor",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "1325 Avenue of the Americas, Floor 27 and 28",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "142 W 57th Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "89-74 162nd Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "Bevmax",
    "address": "667 Madison Avenue, Floor 4, 5",
    "priceText": null,
    "description": "",
    "sourceUrl": "https://www.bevmaxoffice.com",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "1501 Broadway (43rd Street & Broadway), Floor 12",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "250 West 55th Street, 17th Floor",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "485 Madison Ave, 7th Floor",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "40 Worth Street, 10th Floor",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "JSuites",
    "address": "31 West 34th Street, Floor 7 and 8",
    "priceText": null,
    "description": "",
    "sourceUrl": "https://www.jaysuites.com",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "369 Lexington Ave, Floor 2 & 3",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "40 Wall Street, Floor 27, 28 & 29",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "515 Madison Ave, Floor 8, 9, & 10",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "315 Madison Avenue & 42nd Street, Floors 3 & 4",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "15 West 38th Street, Floor Ground & 4-12",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "30 Broad Street, Floor 14",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "1441 Broadway, Floor 5 & 6",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "159 West 25th street floor 4, 5, 7, & 9",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "41 Flatbush Ave, Floor 2",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "Virgo",
    "address": "1345 Avenue of the Americas, 2nd Floor",
    "priceText": null,
    "description": "",
    "sourceUrl": "https://www.virgobc.com",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "NYC Office Suites",
    "address": "1350 Ave of Americas",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "1270 Ave of Americas",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "733 3rd Ave",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "420 Lexington Ave (Graybar Building)",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "122 East 42nd Street (Chanin Building)",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "1140 Ave of Americas",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "Workhouse",
    "address": "21 West 46th street New York",
    "priceText": null,
    "description": "",
    "sourceUrl": "https://www.workhousenyc.com",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "Studio - Tishman Speyer",
    "address": "1 Rockefeller Plaza, Floors 2 and 6",
    "priceText": null,
    "description": "",
    "sourceUrl": "https://www.yourstudio.com",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "666 Third Ave, Floor 6",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "11 West 42nd Street, Floor 2",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "300 Park Avenue, Floor 2 and 5",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "66 Hudson Blvd E, Floor 24",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "28-07 Jackson Avenue, LIC,  Floor 5, 8, 9, 11, 14, 15, 16 ",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "1230 Avenue of the Americas, Floor 15, 16, 18, 19",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "600 5th Ave, Floor 2 and 11",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "156 West 56th Street, Floor 2 and 3",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "175 Varick Street, Floor 1, 2, 4",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "Elevated",
    "address": "1120 Avrnue of the Americas, Floor 4, 14, 15, 18",
    "priceText": null,
    "description": "",
    "sourceUrl": "https://www.elevatedny.com",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "Industrious",
    "address": "190 Bowery Street (Fall 2026 opening)",
    "priceText": null,
    "description": "",
    "sourceUrl": "https://www.industriousoffice.com",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "902 Braodway (June 2026 opening)",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "156 5th Avenue (Fall 2026 opening)",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "386 Park Avenue South  (June 2026 opening)",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "12 East 49th Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "875 Third Avenue (June 2026 opening)",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "390 park Avenue (June 2026 opening)",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "5 Columbus Circle",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "1900 Broadway",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "594 Dean Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "356 Wythe Avenue",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "200 Broadway",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "1002 Dean Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "11 Park Place",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "25 Broadway",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "107 Greenwich Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "175 Greenwich Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "325 Hudson Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "41 East 11th Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "609 Greenwich Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "215 Park Avnue South",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "860 Broadway",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "120 East 23rd Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "119 West 24th Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "776a 6th Avenue",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "560 Lexington Avenue",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "183 Madison Avenue",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "251 West 30th Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "250 West 34th Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "261 Madison Avenue",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "119 West 24th Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "25 West 39th Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "1411 Broadway",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "200 West 41st Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "135 West 50th Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "540 Madison Avenue",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "110 East 42nd Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "28 West 44th Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "31 Hudson Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "WeWork",
    "address": "199 Water Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "https://www.wework.com",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "450 Lexington Avenue",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "368 9th Avenue",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "8 W 126th Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "430 Park Avenue",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "18 West 18th Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "135 Madison Ave",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "500 7th Avenue",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "85 Broad Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "575 Lexington Avenue",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "148 Lafayette Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "160 Varick Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "1450 Broadway",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "Doc 72 at the Brooklyn Navy Yard",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "450 Park Avenue South",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "408 Broadway",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "154 W 14th Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "750 Lexington Avenue",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "115 Broadway",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "134 N 4th Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "575 Fith Avenue",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "33 Irving Place",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "379 W Broadway",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "195 Montague Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "1460 Broadway",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "27 East 28th Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "Dumbo Heights (77 Sands)",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "524 Broadway",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "135 W 41st Street",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "250 Broadway",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "Servcorp",
    "address": "1 World Trade Center, Floor 85",
    "priceText": null,
    "description": "",
    "sourceUrl": "https://www.servcorp.com",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "1330 Avenue of the Americas, Floor 23",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "17 State Street, Floor 40",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "Emerge212 / Elevated",
    "address": "1185 Avenue of the Americas, Floor 2 & 3",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "3 Columbus Circle, Floor 15 & 16",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "125 Park Avenue, Floor 25 & 26",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "Inspire Workspace",
    "address": "7 World Trade Center (250 Greenwich St), Floor 46",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "4 World Trade Center (150 Greenwich St), Floor 29",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "Stark Office Suites",
    "address": "110 East 59th Street (Park Avenue), Floor 22 & 23",
    "priceText": null,
    "description": "",
    "sourceUrl": "https://www.starkofficesuites.com",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "",
    "address": "60 East 42nd Street (One Grand Central) Floor 40,46, 47",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "Excelsior (high end)",
    "address": "825 3rd Avenue, Floor 21",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "Excelsior (high end)",
    "address": "717 Fifth Avenue, Floor 12A and 14 (opening in August 26)",
    "priceText": null,
    "description": "",
    "sourceUrl": "",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "Industrious",
    "address": "776A 6th Avenue New York, NY 10001",
    "priceText": "On request",
    "description": "Plug-and-play private office and coworking space.",
    "sourceUrl": "https://www.industriousoffice.com/m/new-york-city",
    "sizeText": null,
    "photos": [
      "OfficePictures/776a-6th-avenue-new-york-ny-10001-office-1.jpg"
    ]
  },
  {
    "provider": "Industrious",
    "address": "12 E 49th St. New York, NY 10017",
    "priceText": "On request",
    "description": "Plug-and-play private office and coworking space.",
    "sourceUrl": "https://www.industriousoffice.com/m/new-york-city",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "Industrious",
    "address": "110 East 42nd Street New York, NY 10017",
    "priceText": "On request",
    "description": "Plug-and-play private office and coworking space.",
    "sourceUrl": "https://www.industriousoffice.com/m/new-york-city",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "Industrious",
    "address": "730 Third Avenue\n\n730 Third Avenue New York, NY 10017",
    "priceText": "On request",
    "description": "Plug-and-play private office and coworking space.",
    "sourceUrl": "https://www.industriousoffice.com/m/new-york-city",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "Industrious",
    "address": "3 World Trade Center\n\n175 Greenwich Street New York, NY 10007",
    "priceText": "On request",
    "description": "Plug-and-play private office and coworking space.",
    "sourceUrl": "https://www.industriousoffice.com/m/new-york-city",
    "sizeText": null,
    "photos": []
  },
  {
    "provider": "Industrious",
    "address": "1000 Dean\n\n1002 Dean St Brooklyn, NY 11238",
    "priceText": "On request",
    "description": "Plug-and-play private office and coworking space.",
    "sourceUrl": "https://www.industriousoffice.com/m/new-york-city",
    "sizeText": null,
    "photos": []
  }
];
